### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by KDSBBS** [wgcban/ChangeFormer#11]
where can we download DSIFN-CD dataset

**Comment by wgcban** [comment]
Hi @KDSBBS,

I have uploaded my processed LEVIR-CD and DSIFN-CD datasets to the DropBox and you can download the final datasets here:

- LEVIR-CD-256: [click here to download](https://www.dropbox.com/sh/lnjxpflvgjijwoj/AAAgWr3xgOjqtTWPVpbLVcfNa?dl=0)
- DSIFN-CD-256: [click here to download](https://www.dropbox.com/sh/i54h8kkpgar1s07/AACK5_jLGS3cP9ocgOMEUJcNa?dl=0)

Accordingly, I have updated the readme file as follows:
https://github.com/wgcban/ChangeFormer/blob/main/README.md#links-to-download-processed-datsets-used-for-trainvaltest

_It is still uploading and will be available to download after a couple of hours._

I also recommend you to see this issue: https://github.com/wgcban/ChangeFormer/issues/12

Let me know if you have more questions!

Best,
Chaminda

**Comment by joostgrunwald** [comment]
This seems possibly resolved, if so please close the issue.
Otherwise here is a link for the dataset:
https://pan.baidu.com/s/19TRsdPiRym9DoV76DukQ5g -Password: hetu

source:
https://github.com/GeoZcx/A-deeply-supervised-image-fusion-network-for-change-detection-in-remote-sensing-images/tree/master/dataset
