### ISSUE TITLE
Can I train this model on ImageNet dataset

### ISSUE THREAD

**Issue by L-xiaolu** [wgcban/ChangeFormer#16]

**Comment by wgcban** [comment]
Hi @L-xiaolu 

Since ImageNet is a classification dataset, you need to do some modifications before you train our model on ImageNet. For the classification task, the Siamese network architecture is not needed. Secondly, you have to replace the MLP decoder with a Global Average Pooling (GAP) layer followed by a set of fully connected layers to support the classification task. With these two main modifications, yes you can train our model on ImageNet for the classification task. Let me know if you need any help during the process and I'm happy to help you. 

Best,

Chaminda.

**Comment by L-xiaolu** [comment]
> Hi @L-xiaolu
> 
> Since ImageNet is a classification dataset, you need to do some modifications before you train our model on ImageNet. For the classification task, the Siamese network architecture is not needed. Secondly, you have to replace the MLP decoder with a Global Average Pooling (GAP) layer followed by a set of fully connected layers to support the classification task. With these two main modifications, yes you can train our model on ImageNet for the classification task. Let me know if you need any help during the process and I'm happy to help you.
> 
> Best,
> 
> Chaminda.

Thank you very much for your help, what I currently want to do is: based on the Siamese network architecture you proposed, without changing the architecture of the model, only by modifying the input and output of the model to train the ImageNet dataset.  This idea is possible?

**Comment by wgcban** [comment]
Hi @L-xiaolu 

I am not exactly sure about what you are trying to do. Without modifying the network I think it is not possible to train our model on the ImageNet dataset because our model is originally designed for change detection whereas ImageNet is a classification dataset. However, if you have any other change detection dataset, you can train our model by modifying the input and output of the model. 

Best,
Chaminda

**Comment by L-xiaolu** [comment]
> Hi @L-xiaolu
> 
> Since now we are going to train for the classification task, you need to basically replace the MLP decoder with a global average pooling layer followed by a set of fully connected layers. To make things easier for you I made a quick sketch for you and you can get an idea from it. ![imagenet_training](https://user-images.githubusercontent.com/38159198/162992117-3a4cc757-5d41-4e9a-88ca-f1a8a38a1674.png)
> 
> Let me know if you have further questions. Best, Chaminda.

Thank you very much for your patience and help, I will try to modify the model according to your tips.
