### ISSUE TITLE
Question about training on LEVIR-CD

### ISSUE THREAD

**Issue by Youskrpig** [wgcban/ChangeFormer#18]
Hi , I found when i load the pretrained model（trained on ade160k dataset）, the keys of checkpoint are not matched.
The pretrained model:
![BFA7F864-1D89-4f31-9F0F-5C87B1584CF8](https://user-images.githubusercontent.com/51428142/163951963-b6ec8da4-3a68-4558-b7bb-1991e5fad3e4.png)
The self.net_G:
![image](https://user-images.githubusercontent.com/51428142/163952175-cdf66f7f-1a74-4153-8323-4a4055af19d3.png)

So the keys of pretrained model are all missing keys.

**Comment by wgcban** [comment]
Hi @Youskrpig 

This is fine. With the pre-trained model we only initialize the weights of convolution and attention modules to speed up the training process. Because of this reason keys were not saved during the pre-training process. In addition, I made couple of small adjustments to final ChangeFormer network which made pre-trained model slightly different from final ChangeFormer architecture. Therefore, when we initialize ChangeFormer with the pre-trained model on ADE, strict=false is used to ignore weights with different sizes.

Hope this answers your question.

Chaminda.

**Comment by Youskrpig** [comment]
> Hi @Youskrpig
> 
> This is fine. With the pre-trained model we only initialize the weights of convolution and attention modules to speed up the training process. Because of this reason keys were not saved during the pre-training process. In addition, I made couple of small adjustments to final ChangeFormer network which made pre-trained model slightly different from final ChangeFormer architecture. Therefore, when we initialize ChangeFormer with the pre-trained model on ADE, strict=false is used to ignore weights with different sizes.
> 
> Hope this answers your question.
> 
> Chaminda.

Sorry, the keys of state_dict of pretrained model is startswith "backbone" or " decode_head", but the encoder and decoder name of self.net_G  are "Tenc_x2" and 'TDec_x2". It means the weight of **all** keys will not be loaded. 
![图片1](https://user-images.githubusercontent.com/51428142/163998465-988efa41-eef9-48b9-a067-b52f783c0618.png)

**Comment by wgcban** [comment]
Now I see your problem. I think I have uploaded pre-trained weights of my very early model and I couldn't find the correct version now. For now, you can start with the pre-trained model on LEVIR-CD or WHU-CD as the starting point. Will that help?

**Comment by Youskrpig** [comment]
> Hi @Youskrpig
> 
> Now I see your problem. I think I have uploaded pre-trained weights of my very early model and I couldn't find the correct version now. For now, you can start with the pre-trained model on LEVIR-CD or WHU-CD as the starting point. Will that help?

Thanks for your reply.

**Comment by chengtianxiu** [comment]
I encountered the same problem,and starting the pre-trained model on LEVIR-CD doesn't seem to work either.How can I solve it?Your help would be greatly appreciated!

**Comment by wgcban** [comment]
Hi @chengtianxiu 

Can you elaborate more on this issue? Starting from pre-trained weights on LEVIR-CD works for me. Can you please give more details on why it is not working?

Best
Chaminda

**Comment by chengtianxiu** [comment]
> Hi @chengtianxiu
> 
> Can you elaborate more on this issue? Starting from pre-trained weights on LEVIR-CD worked for me. Can you please give more details on where it is not working?
> 
> Instead, you can initialize the model randomly too.
> 
> Best Chaminda

Sorry I didn't express myself clearly. When I used "run_ChangeFormer_DSIFN.sh" in scripts folder to train on DSIFN-CD, I set the pre-trained model to “CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256/best_ckpt.pt” which you provided. The training process went very well,and I saved the model I trained.

But When I used "eval_ChangeFormer_DSIFN.sh",I set "checkpoints_root" and "checkpoint_name" to the model I trained. The displayed result is "raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(,  RuntimeError: Error(s) in loading state_dict for ChangeFormerV6: ".  I have tried changing line 70 in models/evaluator.py to "self.net_G.load_state_dict(checkpoint['model_G_state_dict'],False)".Although no errors are reported, the model is completely useless for change detection.I would like to ask how to solve this, which is the same as the problem Youskrpig encountered.

In addition, During the process "Train on  LEVIR-CD/DSIFN-CD",if we set “split_val=test",can we see the test results without having to "Evaluate on LEVIR/DSIFN-CD".
Your help would be greatly appreciated

chengtianxiu

![Z9RKS_T7()9TGTNX)I30 (V](https://user-images.githubusercontent.com/94813974/164976767-f2b2c1e2-8659-4c21-bc84-971ba5c34883.png)
!

**Comment by wgcban** [comment]
Hi @chengtianxiu 

Sorry for the late reply. I am happy that you were able to train the ChangeFormer on the DSIFN dataset. Are you sure that you set the correct path/name of the pre-trained model? Can you please double-check? If you are still getting this error can you copy-paste the exact error details here, so that I can look into it?

Notes: settings strict=False when loading the state dictionary won't help during the inference process because we want to load all the weights.
I am wondering how the state dictionary changed when you go from the training to the testing phase if you specified the path to correct the pre-trained model?

Best,
Chaminda

**Comment by wgcban** [comment]
@chengtianxiu 
Also pls make sure that you specify the correct model parameters (i.e., embedding dim) in the script file.

**Comment by chengtianxiu** [comment]
> @chengtianxiu Also pls make sure that you specify the correct model parameters (i.e., embedding dim) in the script file.

Okay, I will check again carefully, thank you very much for your answer！
