### ISSUE TITLE
about pre_training

### ISSUE THREAD

**Issue by z1zzzz1** [wgcban/ChangeFormer#30]
Hello author, I noticed in your question with other people that the existing ADE160K pre-training model（pretrained_changeformer.pt） is not the final ChangeFormer_v6 pre-training model, so when I want to use pre-training to train the dataset, do I need to use (
CD_ChangeFormerV6_LEVIR_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_True_multi_infer_False_shuffle_AB_False_embed_dim_256.zip) model under this file? If so, can I use this model to train other datasets such as DSIFN?
Looking forward to your answer, thank you

**Comment by wgcban** [comment]
@z1zzzz1 Yes, you can use the model trained on either dataset as the pre-trained model (either LEVIR-CD or DSIFN-CD)
Thanks

**Comment by z1zzzz1** [comment]
Hello, the author, after trying to use the following pre training model (cd_changeformerv6_levy/dsifn_b16_lr0.0001_adamw_train_test_200_linear_ce_multi_train_true_multi_infer_false_shuffle_ab_false_embedded_dim_256), there will still be a problem that the weights of each layer do not match. If you can, please answer it for me, thank you
![QQ图片20220802095439](https://user-images.githubusercontent.com/102965475/182275085-b98e1289-063e-42b9-b1e2-3bf53fb513b4.png)

**Comment by wgcban** [comment]
@z1zzzz1 I think this shouldn't be the case. Since this model is trained for change detection and since it is working perfectly during inference, is it possible to miss parameters? I am wondering whether you set up the exact model parameters in the corresponding DSIFN dataset config file. If that is not the case, this behavior can be expected and you can set `strict=false` during initializing to remove this error so that it will discard initialing those weights.

**Comment by z1zzzz1** [comment]
thanks for ur reply! and i will check my settings carefully
