### ISSUE TITLE
Some Questions about Code and Paper Details

### ISSUE THREAD

**Issue by zafirshi** [wgcban/ChangeFormer#35]
Hi~ Thx for your great work, :clap:  it's really inspired a lot in siamese Transformer network realizing.

However, I still have some questions about the code implementation and the details of the paper.

1. In the code, the implementation of Sequence Reduction was completed through the Conv2d non-overlapping cutting feature map before MHSA. https://github.com/wgcban/ChangeFormer/blob/9025e26417cf8f10f29a48f34a05758498216465/models/ChangeFormer.py#L316 The effect of the implementation is similar to that of the first shape and then linear projection in the paper, but this code implementation will result in a reduction of the sequence length R^2 times (similar to the idea of cutting the image into 16 * 16 patches at the beginning of the ViT). However, the formula 2 in the paper shows that the reduction is  times. Is there an error here?

2. In this code:https://github.com/wgcban/ChangeFormer/blob/9025e26417cf8f10f29a48f34a05758498216465/models/ChangeFormer.py#L507 the actual code implements two skips connected. In the pink block diagram of Transformer Block explained in the upper right corner of Fig1 in the paper, do you need to draw two skips connected?（Add skip bypass connecting Sequence Reduction input an MHSA output）

3. About Depth-wise Conv in Transformer Block as PE.Why you do this? How to realize position coding(Can you explain it)? Why is this effective?

4. `patch_block1` is not used in the code. What is this module used for? Why is it inconsistent with the previous `block1` dimension? （`dim=embed_dims[1]` and `dim=embed_dims[0]` respectively）https://github.com/wgcban/ChangeFormer/blob/9025e26417cf8f10f29a48f34a05758498216465/models/ChangeFormer.py#L52

Looking forward to your early reply!:smiley:

**Comment by wgcban** [comment]
Hi @zafirshi 

Here I try to answer your questions. 

Q1:

You are completely correct. This is a mistake in the paper. Using conv2d layer with stride = kernel_size = sr_ratio results in the output having a shape of H/R x W/R, where H and W are the initial height and width of the image and R is the reduction ratio; hence reducing the sequence length by a factor of R^2. We appreciate your pointing out this mistake in the paper, and we will correct equation 2 in the next revision.

**Comment by wgcban** [comment]
@zafirshi 

Q2:

Here also, your assessment is correct, and I intentionally avoided this skip connection in the Figure because I did not want to unnecessarily complicate it. 

As a side note, having this skip connection slightly improves the model convergence and results, as I remember, because it helps the network to avoid the vanishing gradient problem.

**Comment by wgcban** [comment]
@zafirshi 

Q3:

We use single 2d convolution in the decoder MLP along with a couple of Linear layers. We included this Conv2D layer with Linear layers for two purposes:

- First, it acts as a positional encoding (learnable) in some way because before the Conv2D, we arrange the pixels into the form of [B,C,H,W] format. So the network is able to identify the positions.
- Secondly, since the Linear layers operate along the embedding dimension, it cants learn the spatial relationship among the neighboring pixels that are extremely needed for change detection. Having a Conv2D layer with kernel_size =3 in between the Linear layers mitigates this problem because it can enhance a representation of a given pixel based on the information from neighboring 8 pixels.

**Comment by wgcban** [comment]
@zafirshi 

Q4:

This module actually not belongs to the final version of the ChangeFormer. I have experimented with multiple ways to improve the ChangeFormer, and this belongs to one such instance. However, I forgot to remove it in the final ChangeFormer version, and this is my mistake. I will remove this in the next pull request. Thanks for pointing out this. I appreciate it.

**Comment by wgcban** [comment]
I hope the above replies answer your questions. Let me know if you want further clarification.

**Comment by zafirshi** [comment]
Thank you for your detailed reply, 

About Q4, I found some parts are redundant when reading the code behind, but this does not affect the effect of the final version of the model, but can learn from the process of modification of your iterative improvement of the network structure, which is very helpful to my engineering practice. 

And finally thank you again for your reply and code!  :smile:
