### ISSUE TITLE
DSIFN dataset splits

### ISSUE THREAD

**Issue by zaidbhat1234** [wgcban/ChangeFormer#52]
@wgcban I had another question regarding the DSIFN dataset that I downloaded from the link in your Readme:
1. Did you use the same train/val/test split for ChangeFormer when you compare its performance with other CD models like BIT?
2. I notice that majority of images used in test.txt are also present in train.txt (164/192) ~85%. Is this something that is an error or it was the same in previous CD works such as BIT? Is this the reason for huge difference in metrics from previous works on DSIFN?

_Originally posted by @zaidbhat1234 in https://github.com/wgcban/ChangeFormer/issues/51#issuecomment-1466909895_

**Comment by wgcban** [comment]
@zaidbhat1234 Hello,

1. yes, if the train/val/test splits are given in the dataset like LEVIR-CD.
2. I think there is some bug while dividing DSIFN dataset into splits. Since they do not provide specific train/val/test splits, I created my own splits. I will examine this issue and try to reproduce the results again. Thanks for pointing out the bug.

**Comment by zaidbhat1234** [comment]
@wgcban Thanks for your response. 

Could you please update the new results in DSIFN dataset once you resolve the bug? Could you also please update the Readme file with the updated train/val/test splits?
